### ISSUE TITLE
Discuss flask shell?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-flask-application-structure#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208455?module_item_id=480470

### Concern

We bring up the `flask shell` as a command and a concept later on in this lesson, but don't discuss what it is or under what contexts we might use it. If we're going to include this material in a later lesson, then we might want to let students know that. Otherwise it could be helpful to discuss what this is, how we use it, and why.

**Comment by professor-ben** [comment]
Hi Matt,

Thanks for the ticket! There's a long story behind this one, but I simply added a note to say that we'll explore it later on, but we won't use it too much due to the volume of dependencies we introduce in Phase 4.

-Ben
