### ISSUE TITLE
A couple of inconsistencies between instructions and screenshots

### ISSUE THREAD

**Issue by baspin94** [learn-co-curriculum/python-p4-flask-application-structure#2]
### Canvas Link

https://learning.flatironschool.com/courses/6259/assignments/233446?module_item_id=547378

### Concern

- README: There is an inconsistency between the text in the screenshot at line 239 of README which displays ‘Welcome to my page!’ and the text used to define that view on line 106, ‘Welcome to my app!’

- README Line 236: I would clarify that entering either http://127.0.0.1:5555/ or localhost:5555 in your browser’s address bar will both work for navigating to the application in the browser. The written instructions tell us to navigate to the app using the IP address, but the screenshots show the app with localhost:5555 in the address bar.

**Comment by professor-ben** [comment]
These have been fixed and clarified, respectively.

Thanks,
Ben
